name: Thank You

on:
  pull_request:
    types: [opened]

jobs:
  thanks:
    runs-on: ubuntu-latest
    steps:
      - uses: donPain/thank-you-action@v1.3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TENOR_TOKEN: ${{secrets.TENOR_TOKEN}}
